### ISSUE TITLE
Hide broadcast message?

### ISSUE THREAD

**Issue by chaoscreater** [B1naryKill3r/HQSolver#10]
Could you add an option in the config to hide the broadcast message? I've already set everything under the Chat section to False and I still get the broadcast message telling me how many players are live, etc.

**Comment by B1naryKill3r** [comment]
Yeah,
When coding I just forgotten about these broadcast messages.
Today I'll make this optional

**Comment by B1naryKill3r** [comment]
From now showing Broadcast Stats is optional.
