### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by anwillcus** [B1naryKill3r/HQSolver#12]
> Traceback (most recent call last):
>   File "C:\HQSolver-master\main.py", line 2, in <module>
>     import requests
>   File "C:\HQSolver-master\requests\__init__.py", line 46, in <module>
>     from .exceptions import RequestsDependencyWarning
>   File "C:\HQSolver-master\requests\exceptions.py", line 9, in <module>
>     from urllib3.exceptions import HTTPError as BaseHTTPError
> ModuleNotFoundError: No module named 'urllib3.exceptions

can someone help me fix this?

**Comment by B1naryKill3r** [comment]
You have Python 3.6 installed?
Also reinstall requests module

**Comment by anwillcus** [comment]
Yes I do have Python 3.6
and i reinstalled requests.

**Comment by B1naryKill3r** [comment]
Try this:
`pip install --upgrade six`

**Comment by anwillcus** [comment]
`Requirement already up-to-date: six in c:\users\colin\appdata\local\programs\python\python36-32\lib\site-packages`

**Comment by anwillcus** [comment]
Fixed it!
