### ISSUE TITLE
Error when starting main.py

### ISSUE THREAD

**Issue by Helpme0822** [B1naryKill3r/HQSolver#13]
When I open main.py it closes immediately after 1 second but I succeeded to take a screenshot of what's written before it closes immediately can someone help me please? 
![sans titre](https://user-images.githubusercontent.com/36854248/37413088-870d753e-27a6-11e8-8b6f-3a29508df2ae.png)

**Comment by Helpme0822** [comment]
and also what do i have to write in the hq_client line in the config.ini file?

**Comment by B1naryKill3r** [comment]
You don't have required dependencies...

Please read README.md...
hq_client is OS/AppVersion (for example Android/1.2.3)

**Comment by Helpme0822** [comment]
i have all dependencies installed even twisted but my computer doesn't want to download the file twisted.internet i think is it because i'm on windows ?

**Comment by B1naryKill3r** [comment]
twisted.internet is a part of twisted module.
You did something wrong while installing dependencies.

Try reinstalling Python

**Comment by chaoscreater** [comment]
I'm getting the following:




> Show active, connecting to socket at https://ws-quiz.hype.space/ws/44151
> Connected
> 
> 
> 
> 
> 
> 
> Question detected.
> Question 10 out of 12
> In the Bible, which son of Jacob has the same mother as Joseph?
> ['Benjamin', 'Levi', 'Simeon']
> 
> Searching
> ['Benjamin', 'Levi', 'Simeon']
> ['bible', 'son', 'jacob', 'mother', 'joseph']
> ['https://en.wikipedia.org/wiki/Rachel', 'https://en.wikipedia.org/wiki/Jacob', 'https://en.wikipedia.org/wiki/Simeon_(son_of_Jacob)', 'http://www.aboutbibleprophecy.com/p34.htm', 'https://www.lds.org/scriptures/gs/joseph-son-of-jacob?lang=eng']
> Running method 1
> {'benjamin': 29, 'levi': 18, 'simeon': 57}
> simeon
> 
> Traceback (most recent call last):
>   File "W:\HQ Trivia\HackQ-Trivia\hq_main.py", line 47, in <module>
>     asyncio.get_event_loop().run_until_complete(networking.websocket_handler(socket, headers))
>   File "C:\Users\Blah\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 467, in run_until_complete
>     return future.result()
>   File "W:\HQ Trivia\HackQ-Trivia\networking.py", line 66, in websocket_handler
>     print(await question.answer_question(question_str, answers))
>   File "W:\HQ Trivia\HackQ-Trivia\question.py", line 67, in answer_question
>     key_nouns.update(search.find_nouns(question, num_words=5, reverse=True))
>   File "W:\HQ Trivia\HackQ-Trivia\search.py", line 33, in find_nouns
>     tokens = word_tokenize(text)
>   File "C:\Users\Blah\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nltk\tokenize\__init__.py", line 128, in word_tokenize
>     sentences = [text] if preserve_line else sent_tokenize(text, language)
>   File "C:\Users\Blah\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nltk\tokenize\__init__.py", line 94, in sent_tokenize
>     tokenizer = load('tokenizers/punkt/{0}.pickle'.format(language))
>   File "C:\Users\Blah\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nltk\data.py", line 834, in load
>     opened_resource = _open(resource_url)
>   File "C:\Users\Blah\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nltk\data.py", line 952, in _open
>     return find(path_, path + ['']).open()
>   File "C:\Users\Blah\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nltk\data.py", line 673, in find
>     raise LookupError(resource_not_found)
> LookupError: 
> **********************************************************************
>   Resource [93mpunkt[0m not found.
>   Please use the NLTK Downloader to obtain the resource:
> 
>   [31m>>> import nltk
>   >>> nltk.download('punkt')
>   [0m
>   Searched in:
>     - 'C:\\Users\\Blah/nltk_data'
>     - 'C:\\nltk_data'
>     - 'D:\\nltk_data'
>     - 'E:\\nltk_data'
>     - 'C:\\Users\\Blah\\AppData\\Local\\Programs\\Python\\Python36-32\\nltk_data'
>     - 'C:\\Users\\Blah\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\nltk_data'
>     - 'C:\\Users\\Blah\\AppData\\Roaming\\nltk_data'
>     - ''
> **********************************************************************

**Comment by B1naryKill3r** [comment]
5 days without answer...
I think that issue is solved.

If no, reopen it.
