### ISSUE TITLE
Changing for another App

### ISSUE THREAD

**Issue by Eazylikesundaymorning** [B1naryKill3r/HQSolver#14]
If I wanted to use this on another app, would it be just as simple as changing config.ini or would I also need to makes changes in config.py?

**Comment by B1naryKill3r** [comment]
What do you mean?
It's called "HQSolver", so i prepared this for *only* "HQ".

You must change connection logic, to use it in another app.

**Comment by yapal** [comment]
Could u plz elaborate the thing "change connection logic". I'm making it as project.

**Comment by yapal** [comment]
Hq client, server ip, authorization key, config.ini, config.py these must be edited. What else changes are required?

**Comment by yapal** [comment]
Actually I must ask u sorry for asking this question. Thank u very much for making time to reply to this. As of now I know api of apps and authorization. Will try and send u back errors be ready bro😂😂😂
