### ISSUE TITLE
Wikipedia solver not working

### ISSUE THREAD

**Issue by maxben34** [B1naryKill3r/HQSolver#16]
When running the solver, wikipedia solver doesn't work. It throws the following error: 

[33mWiki: Warning! It seems that we have problem getting info from Wikipedia.[0m
Wiki: [0, 0, 0]
************************************* Wikipedia solver couldn't guess the answer! **************************************

**Comment by B1naryKill3r** [comment]
It's common error, rest of solvers should work correctly.
