### ISSUE TITLE
cryptography issue

### ISSUE THREAD

**Issue by bfcb** [B1naryKill3r/HQSolver#18]
![capture](https://user-images.githubusercontent.com/37844162/38685279-842d24fe-3e3f-11e8-9048-e29198226831.JPG)

i have all the requirements installed but I am getting this crytography error when i try to run the py.
Im using win10 ubuntu with python3.6 to run this.

**Comment by B1naryKill3r** [comment]
Try to install Python3.6 natively on Windows

**Comment by B1naryKill3r** [comment]
Closed due no response
