### ISSUE TITLE
ImportError: cannot import name get_terminal_size

### ISSUE THREAD

**Issue by JillzTom** [B1naryKill3r/HQSolver#22]
I'm having this issue: 
```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from shutil import get_terminal_size
ImportError: cannot import name get_terminal_size
```

**Comment by JillzTom** [comment]
It was just a python version issue.

**Comment by U-r-Unknown** [comment]
I have working bot which works on all trivia games. No worries about ban as this is PC software. No need of any programming knowledge. If interested mail me onlineuse321@gmail.com. (setting up this is frustrating)
