### ISSUE TITLE
Unicode Error during broadcast

### ISSUE THREAD

**Issue by HyperManTT** [B1naryKill3r/HQSolver#24]
Hey,

During the broadcast, I was spontaneously getting the below error:

`File "/Users/randy/Desktop/HQSolver/solver.py", line 143, in showQuestion
    print(tempPrint.center(get_terminal_size()[0]))
builtins.UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 37: ordinal not in range(128)`

This causes the connection to then be lost. Any ideas on why this is sporadically happening?

**Comment by B1naryKill3r** [comment]
It seems that some incorrect characters are being sent.

Sorry, but I lost interest in making HQSolver due to lost interest at trivia games at all.

**Comment by HyperManTT** [comment]
No worries, I'll continue development on my own. Thanks for the work you did so far though!

**Comment by B1naryKill3r** [comment]
Thanks you @KiloSierraCharlie for fixing that issue, I really appreciate this!
