### ISSUE TITLE
How do i found my authorization_key

### ISSUE THREAD

**Issue by rrajkowski** [B1naryKill3r/HQSolver#27]
from the ios app or do i generate it somehow?

**Comment by B1naryKill3r** [comment]
By sniffing game http(s) requests

It's part of header: `Authorization: Bearer <your authorization key is here>`

**Comment by B1naryKill3r** [comment]
Closed due 1 week of no response

**Comment by rrajkowski** [comment]
@B1naryKill3r would i sniff the http req with Charles or other tool?

**Comment by B1naryKill3r** [comment]
Yeah
