### ISSUE TITLE
failed to run even after modified the config file 

### ISSUE THREAD

**Issue by manofsteel2017** [B1naryKill3r/HQSolver#3]
google_api_key = YOUR_GOOGLE_API_KEY
google_cse_id = YOUR_CUSTOM_SEARCH_ENGINE_ID

do these things show up in charles as well?

your readme file has no info at all

I understand you aren't eager to help people but you will get asked  the same questions  many times if you aren't clear in your instructions 

Thanks

**Comment by gjacobs314** [comment]
Because this is meant for advanced users who know what they are doing. You have to create a Google CSE and use that ID and then create an API key too (through Google) and put that in the api_key part. You don't find it in Charles because you have to make it.

**Comment by B1naryKill3r** [comment]
You must create Google API Key and Custom Search Engine (and get from it ID).
Not the real issue, closing...
