### ISSUE TITLE
Google-Search-API	1.1.14?

### ISSUE THREAD

**Issue by sillibird** [B1naryKill3r/HQSolver#31]
Hi, it says to use Google-Search-API 1.1.14, but the latest I can find is 1.1.13. In addition, the install of it fails every time with

`ModuleNotFoundError: No module named 'modules'`

What am I missing?

**Comment by B1naryKill3r** [comment]
You need to install everything from `pip install -r requirements.txt`

**Comment by B1naryKill3r** [comment]
...or install it manually `pip install git+https://github.com/abenassi/Google-Search-API/`

**Comment by B1naryKill3r** [comment]
I'm guessing that this issue has been fixed. Closing. Re-open if you still need help
