### ISSUE TITLE
Error when running with Python

### ISSUE THREAD

**Issue by nolanplatt** [B1naryKill3r/HQSolver#7]
![screen shot 2018-02-28 at 5 39 05 pm](https://user-images.githubusercontent.com/20466654/36822731-58dcf494-1cae-11e8-946d-020c71ba5e34.png)
Thank you!

**Comment by gjacobs314** [comment]
Install the requirements with: pip install requirement

**Comment by B1naryKill3r** [comment]
You must install all requirements (read README.md) for more info
