### ISSUE TITLE
list index out of range on solver

### ISSUE THREAD

**Issue by svjacob** [B1naryKill3r/HQSolver#9]
I actually won using this code tonight! Some of the questions the solver couldn't complete or returned no answers, so I had to guess.

Here is one of the exceptions that happened during the show:

> *************************** Naive solver couldn't guess the answer! ****************************
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Users/stevenjacob/Downloads/other/HQSolver/solvers/wiki.py", line 20, in solve
>     self.correctPageNames = self.searchForPotencialPages()
>   File "/Users/stevenjacob/Downloads/other/HQSolver/solvers/wiki.py", line 72, in searchForPotencialPages
>     potencialPages.append(searchResults[0])  # If not found try first page
> IndexError: list index out of range

**Comment by B1naryKill3r** [comment]
Happy to hear that!

I'll fix that today. Stay tuned.

**Comment by B1naryKill3r** [comment]
Fixed that
